[package]
name = "spatula"
version = "0.1.1"
authors = ["Nicholas Guarino <me@ndguarino.com>"]
edition = "2018"

[dependencies]
async-std = { version = "1.9", features = ["attributes", "tokio02", "tokio1"] }
egg-mode = "0.15"
futures = "0.3"
serenity = "0.10"
